name: GitHub Actions
on:
  push:
    branches: 
      - main
      - develope
      - alexey
      - danil
      - daniil
      - "rostyan*"
  pull_request:
    branches: 
      - main
      - develope
      - alexey
      - danil
      - daniil
      - "rostyan*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse3 libfuse3-dev cmake g++ pkg-config


      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
